# Generated by Django 5.1.6 on 2025-02-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapHistoricReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
                ('capmo', models.CharField(max_length=20)),
                ('mbshp', models.IntegerField()),
            ],
        ),
    ]
