# Generated by Django 5.1.6 on 2025-02-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_caphistoricreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caphistoricreport',
            options={'managed': False},
        ),
    ]
