# Generated by Django 5.1.6 on 2025-02-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_caphistoricreport_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='caphistoricreport',
            table='caphistoric_report_to_use_1year',
        ),
    ]
