# Generated by Django 5.1.6 on 2025-03-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_caphistoricreport_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterModelTable(
            name='caphistoricreport',
            table='caphistoric_report_to_use',
        ),
    ]
