# Generated by Django 5.1.6 on 2025-03-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_delete_item_alter_caphistoricreport_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapHistoricReportOneYear',
            fields=[
                ('center', models.CharField(db_column='CENTER', db_index=True, max_length=100)),
                ('plan', models.CharField(db_column='PLAN', db_index=True, max_length=100)),
                ('lob', models.CharField(db_column='LOB', max_length=50)),
                ('mbshp', models.IntegerField(db_column='MBSHP')),
                ('id', models.CharField(db_column='ID', max_length=50, primary_key=True, serialize=False)),
                ('hic_num', models.CharField(db_column='HIC_NUM', max_length=50)),
                ('mcaid_num', models.CharField(db_column='MCAID_NUM', max_length=50)),
                ('membname', models.CharField(db_column='MEMBNAME', max_length=200)),
                ('dob', models.DateField(db_column='DOB', db_index=True)),
                ('age', models.IntegerField(db_column='AGE')),
                ('sex', models.CharField(db_column='SEX', max_length=1)),
                ('address', models.CharField(db_column='ADDRESS', max_length=255)),
                ('city', models.CharField(db_column='CITY', max_length=100)),
                ('st', models.CharField(db_column='ST', max_length=2)),
                ('zip', models.CharField(db_column='ZIP', max_length=10)),
                ('county', models.CharField(db_column='COUNTY', max_length=100)),
                ('phonenumber', models.CharField(db_column='PHONENUMBER', max_length=20)),
                ('capmo', models.CharField(db_column='CAPMO', db_index=True, max_length=20)),
                ('pcpname', models.CharField(db_column='PCPNAME', max_length=255)),
                ('stat', models.CharField(blank=True, db_column='STAT', max_length=50, null=True)),
            ],
            options={
                'db_table': 'webreports.caphistoric_report_to_use_1year',
                'managed': False,
            },
        ),
    ]
