# Generated by Django 5.1.6 on 2025-03-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_caphistoricreportoneyear'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='caphistoricreportoneyear',
            table='caphistoric_report_to_use_1year',
        ),
    ]
