# Generated by Django 5.1.6 on 2025-03-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_caphistoricreportoneyear_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('center', models.CharField(db_column='CENTER', db_index=True, max_length=100)),
                ('plan', models.CharField(db_column='PLAN', db_index=True, max_length=100)),
                ('lob', models.CharField(db_column='LOB', max_length=50)),
                ('member_id', models.CharField(db_column='MEMBER_ID', max_length=50, primary_key=True, serialize=False)),
                ('medicare_id', models.CharField(db_column='MEDICARE_ID', max_length=50)),
                ('medicaid_id', models.CharField(db_column='MEDICAID_ID', max_length=50)),
                ('member_name', models.CharField(db_column='MEMBER_NAME', max_length=200)),
                ('dob', models.DateField(db_column='DOB', db_index=True)),
                ('age', models.IntegerField(db_column='AGE')),
                ('sex', models.CharField(db_column='SEX', max_length=1)),
                ('address', models.CharField(db_column='ADDRESS', max_length=255)),
                ('city', models.CharField(db_column='CITY', max_length=100)),
                ('st', models.CharField(db_column='ST', max_length=2)),
                ('zip', models.CharField(db_column='ZIP', max_length=10)),
                ('county', models.CharField(db_column='COUNTY', max_length=100)),
                ('phonenumber', models.CharField(db_column='PHONENUMBER', max_length=20)),
                ('mos', models.CharField(db_column='MOS', db_index=True, max_length=20)),
                ('mshp', models.IntegerField(db_column='MSHP')),
                ('pcpname', models.CharField(db_column='PCPNAME', max_length=255)),
                ('age_group', models.CharField(db_column='AGE_GROUP', max_length=50)),
                ('stat', models.CharField(blank=True, db_column='STAT', max_length=50, null=True)),
            ],
            options={
                'db_table': 'membership',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CapHistoricReport',
        ),
        migrations.DeleteModel(
            name='CapHistoricReportOneYear',
        ),
    ]
